<a href="https://colab.research.google.com/github/choi-yh/DataStructure/blob/master/2_3_SparseMatrix(HW2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* **희소행렬** 이란: 행렬 원소에 0이 많이 포함된 행렬  
* 희소행렬에서의 0도 메모리를 차지한다.  
* *Term Document Matrix*가 대표적인 희소행렬 (big data에서)  

* (row, column, element)의 형태로 저장한다. $\Rightarrow$ 효율적으로 저장가능  


* SparseMatrix 자료구조  
    * 행렬의 dimension m, n 을 입력받아 희소행렬 리스트를 [[m, n, 0]]로 초기설정한다.  
    * append 메소드: [i, j, value] 형태의 리스트를 희소행렬 리스트에 추가한다.  
    * shape 메소드: 희소행렬의 dimension을 리턴한다.
    * getValue 메소드: i, j 행렬값을 리턴한다.
    * print 메소드: 희소행렬을 일반적 행렬 형태로 출력한다. (0으로 구성된 m,n array를 만들고 i,j 행렬값을 업데이트하여 출력한다.)

In [0]:
import numpy as np
class SparseMatrix:
    def __init__(self, m, n):
        self.s = [[m, n, 0]] # header
        self.m = m
        self.n = n

    def append(self, i, j, value):
        self.s.append([i, j, value])
        self.s[0][2] += 1
        
    def shape(self):
        return self.m, self.n

    def getValue(self, row, col):
        for i in range(1, self.s[0][2]+1):
            if (self.s[i][0] == row) and (self.s[i][1] == col):
                return self.s[i][2]
        return 0

    def print(self):
        mat = np.zeros((self.m, self.n))
        for i in range(1, len(self.s)):
            mat[self.s[i][0]-1, self.s[i][1]-1] = self.s[i][2]
        print(mat)
    
    # 행렬 덧셈 메소드
    @classmethod
    def add(cls, a, b):
        if a.shape() != b.shape():
            print("두 행렬의 차원이 다릅니다.")
            return None
        else:
            mat = SparseMatrix(a.m, a.n)
            u = set()
            for i in range(1, len(a.s)):
                u.add((a.s[i][0], a.s[i][1]))
            for j in range(1, len(b.s)):
                u.add((b.s[j][0], b.s[j][1]))

            for tmp in list(u):
                val = a.getValue(tmp[0], tmp[1]) + b.getValue(tmp[0], tmp[1])
                if val != 0:
                    mat.append(tmp[0], tmp[1], val)
            return mat
    
    # 전치행렬 메소드
    @classmethod
    def transpose(cls, a):
        t_a = SparseMatrix(a.n, a.m)
        for i in range(1, len(a.s)):
            val = a.getValue(a.s[i][0], a.s[i][1])
            if val != 0:
                t_a.append(a.s[i][1], a.s[i][0], val)
        return t_a       

    # 행렬 곱셈 메소드 (HW 2)
    @classmethod
    def mul(cls, a, b):
        m = a.m
        n = a.n
        l = b.n
        if a.n != b.m:
            print("두 행렬의 곱셈을 할 수 없습니다.")
            return None
        else:
            c = SparseMatrix(m, l)
            for i in range(1, m+1):
                for j in range(1, l+1):
                    val = 0
                    for k in range(1, n+1):
                        val += a.getValue(i, k) * b.getValue(k, j)
                    if val != 0:
                        c.append(i, j, val)
            return c


a = SparseMatrix(3,3)
b = SparseMatrix(3,3)

a.append(1,1,1)
a.append(2,2,2)
a.append(3,3,3)

b.append(1,1,4)
b.append(1,2,7)
b.append(2,3,2)
b.append(3,3,1)

a.print()
b.print()

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
[[4. 7. 0.]
 [0. 0. 2.]
 [0. 0. 1.]]


In [0]:
c = SparseMatrix.add(a, b)
c.print()

[[5. 7. 0.]
 [0. 2. 2.]
 [0. 0. 4.]]


In [0]:
t_c = SparseMatrix.transpose(c)
t_c.print()

[[5. 0. 0.]
 [7. 2. 0.]
 [0. 2. 4.]]


In [0]:
d = SparseMatrix.mul(a, b)
d.print()

[[4. 7. 0.]
 [0. 0. 4.]
 [0. 0. 3.]]
